### ISSUE TITLE
Error Install Owl 1.2

### ISSUE THREAD

**Issue by maxkuttner** [owlbarn/owl#693]
Build failure on Fedora 42 / OCaml 5.3.0: `too many arguments to function 'std_gaussian_rvs'`

### Environment

* **OS:** Fedora 42 (x86\_64)
* **opam:** 2.4.1
* **OCaml:** `ocaml-base-compiler.5.3.0`
* **owl:** 1.2
* **dune:** 3.20.2

### Steps to Reproduce

1. Create / use a switch with OCaml 5.3.0.
2. Run:

   ```sh
   opam install owl
   ```
3. (Also reproducible when building the repo directly with `dune build`.)

### Expected Behavior

Package builds and installs successfully.

### Actual Behavior

Build fails during compilation of `owl`:

```
#=== ERROR while compiling owl.1.2 ============================================#
# command     dune build -p owl -j 3
# exit-code   1
```

Relevant excerpt from `~/.opam/log/owl-*/owl-*.out`:

```
src/owl/stats/owl_stats_dist_exponpow.c:36:14: error: too many arguments to function ‘std_gaussian_rvs’; expected 0, have 1
```

Full install plan & logs (truncated):

```text
The following actions will be performed:
  ∗ base v0.17.3
  ∗ bigarray-compat 1.1.0
  ∗ camlzip 1.13
  ∗ conf-openblas 0.2.2
  ∗ conf-pkg-config 4
  ∗ conf-zlib 1
  ∗ csexp 1.5.2
  ∗ ctypes 0.23.0
  ∗ dune 3.20.2
  ∗ dune-configurator 3.20.2
  ∗ integers 0.7.0
  ∗ npy 0.0.9
  ∗ ocaml_intrinsics_kernel v0.17.1
  ∗ ocamlfind 1.9.8
  ∗ owl 1.2
  ∗ owl-base 1.2
  ∗ sexplib0 v0.17.0
  ∗ stdlib-shims 0.3.0
...
[ERROR] The compilation of owl.1.2 failed at "dune build -p owl -j 3".
```

---

It looks like `std_gaussian_rvs` is being called with an argument in `src/owl/stats/owl_stats_dist_exponpow.c`, but its header declares a zero-argument signature. This might be a mismatch between the declaration and the definition (or a signature change elsewhere that didn’t propagate).

Can you help me with this problem. I have little knowledge about owl and/or ocaml yet and would highly appreciate some pointers to fix this problem.

Happy to provide the full `~/.opam/log/owl-*.out` and `env` files if helpful. 

PS: I have not tried to build it with by adapting the signature ... not even sure if that is the problem since it builds on my ubuntu 22.04 LTS machine and the relevant src files have not changed in years.

**Comment by tristan-f-r** [comment]
GCC 15.3 recently came out, with an entry in [their changelog](https://www.gnu.org/software/gcc/gcc-15/changes.html):

> To aid the transition to C23, various diagnostics have been enhanced to clarify type errors such as incompatible function types, incorrect argument counts, and those involving bool.

This means that for people who update GCC to the latest version, the current owl release at the time of writing (1.2 without the associated #694 patch) will not build.
